# Examen Mathematics for Machine Learning

- Naam: Ruben Priels
- Klas: 2E2

Indienen gebeurt door dit notebook uit te voeren en met de uitvoer intact op te laden in de Examen-opdracht.
Laad ook een PDF-versie van je notebook op in de examentool.

Alle code die je moet schrijven moet je invullen tussen
`### JOUW CODE HIER` en  `### EINDE JOUW CODE HIER`.  

Vaak moet je ook een korte vraag beantwoorden, gebaseerd op de uitvoer van je code of een meer theoretische vraag. Bv.
- Wat is het antwoord op de ultieme vraag over het Leven, het Universum, en Alles? HIER ANTWOORDEN

Dan vervang je deze HIER ANTWOORDEN door 42.

De import statements die we gaan gebruiken staan hieronder. Voeg zelf **geen nieuwe import statements toe**.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Vraag 1. Enkele korte opgaves (/10)

### Opgave 1.1 (/2)

Creëer op een efficiënte manier een matrix met 20 rijen en 10 kolommen die de getallen 1 tem 200 bevat in omgekeerde volgorde.

De eerste rij bevat dus de getallen 200 tem 191, de tweede rij 190 tem 181 en de laatste rij 10 tem 1

In [ ]:
### JOUW CODE HIER ###
a = np.arange(1, 201)
a = a[::-1]
a.reshape(20, 10)
### EINDE JOUW CODE HIER ###

array([[200, 199, 198, 197, 196, 195, 194, 193, 192, 191],
       [190, 189, 188, 187, 186, 185, 184, 183, 182, 181],
       [180, 179, 178, 177, 176, 175, 174, 173, 172, 171],
       [170, 169, 168, 167, 166, 165, 164, 163, 162, 161],
       [160, 159, 158, 157, 156, 155, 154, 153, 152, 151],
       [150, 149, 148, 147, 146, 145, 144, 143, 142, 141],
       [140, 139, 138, 137, 136, 135, 134, 133, 132, 131],
       [130, 129, 128, 127, 126, 125, 124, 123, 122, 121],
       [120, 119, 118, 117, 116, 115, 114, 113, 112, 111],
       [110, 109, 108, 107, 106, 105, 104, 103, 102, 101],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31

### Opgave 1.2 (/4)

- Maak een matrix $4\times 3$ matrix met de kwadraten van de getallen 0 tem 11.
- Bereken en print vervolgens een array die het gemiddelde van elke rij bevat. Het resultaat is een array van lengte 4



In [56]:
### JOUW CODE HIER ###
a = np.array([0*0, 1*1, 2*2, 3*3, 4*4, 5*5, 6*6, 7*7, 8*8, 9*9, 10*10, 11*11])
a.reshape(4, 3)
b = np.array([a.mean])
### EINDE JOUW CODE HIER ###

[<built-in method mean of numpy.ndarray object at 0x7ba2c58858f0>]


### Opgave 1.3 (/4)

Maak een geheeltallige $10\times 10$ matrix met het volgende patroon:
$$
\begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1  & 1 & 1 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 0 & 0  & 0 & 0 & 1 & 1 \\
1 & 1 & 1 & 1 & 1 & 1  & 1 & 1 & 1 & 1 \\
\end{bmatrix}
$$
Gebruik hoogstens 2 statements.

In [69]:
### JOUW CODE HIER ###
np.zeros((10, 10))
### EINDE JOUW CODE HIER ###

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Vraag 2. De QR-decompositie (/22)

In deze oefening implementeer je een alternatieve methode om de QR-decompositie van een vierkante matrix te berekenen.

#### Methode `maak_nul` (/2)

Implementeer een methode `maak_nul(x, index)` die een numpy array `x` en een index `index` meekrijgt en een array retourneert waarbij alle elementen vanaf index `0` t.e.m. index `index-1` gelijk zijn aan nul. Alle andere elementen blijven ongewijzigd.  Je mag de originele array `x` niet aanpassen! Hieronder een voorbeeld:

```python
maak_nul(np.array([-1, -2, 3, 4, 5]), 2)  # array([0,0,3,4,5])
```

In [31]:
def maak_nul(x, index):
    ### JOUW CODE HIER ###
    a = np.copy(x)
    for i in range(index) :
      a[i] = 0
    return a
    ### EINDE JOUW CODE HIER ###


array([0, 0, 3, 4, 5])

In [ ]:
# Gebruik deze code om je methode te testen.
tmp = np.array([1,2,3,4,5])
print(maak_nul(tmp, 2))
print(f"de array tmp is nu: {tmp}")

#### Methode `eenheidsvector` (/2)

Implementeer een methode `eenheidsvector(n, i)` die een numpy array van lengte `n` teruggeeft
bestaande uit nullen behalve het element op plaats `i` dat gelijk is aan 1.

```python
eenheidsvector(5, 3)  # array([0., 0., 0., 1., 0.])
```

In [36]:
def eenheidsvector(n, i):
    ### JOUW CODE HIER
    a = np.zeros(n)
    a[i] = 1
    return a
    ### EINDE JOUW CODE HIER

array([0., 0., 0., 1., 0.])

#### Methode `maak_spiegeling` (/3)

Schrijf een methode `maak_spiegeling(u)` die een numpy array `u` meekrijgt en een matrix retourneert die een Householder reflectie voorstelt.

De Householder reflectie is gedefinieerd als:
$$
\mathbf{H} = \mathbf{I} - 2\mathbf{v}\mathbf{v}^T,\quad \text{met } \mathbf{v} = \frac{\mathbf{u}}{\lVert \mathbf{u}\rVert}.
$$
Hierbij is $\mathbf{I}$ de eenheidsmatrix van de gepaste grootte en $\mathbf{v}\mathbf{v}^T$ is het **uitwendig product** van $\mathbf{v}$ met zichzelf.

Je kan wiskundig controleren dat $\mathbf{H}$ een orthogonale matrix is (maar je moet dit niet doen in deze opgave).

In [15]:
def maak_spiegeling(u):
    ### JOUW CODE HIER
    assert len(x.shape) == 1, "geen vector"
    v = u/np.linalg.norm(u)
    I = np.eye(u)
    H = I - 2*v*v.shape[::-1]
    ### EINDE JOUW CODE HIER

#### Implementatie van de QR-decompositie (/15)

Gegeven een vierkante  $n\times n$ matrix $\mathbf{A}$. De QR-decompositie van $\mathbf{A}$ wordt berekend door het uitvoeren van $n-1$ Householder reflecties.

In het bijzonder werkt de QR-decompositie als volgt:
- Stel `R` gelijk aan de originele matrix `A` (maar let op dat je `A` niet aanpast).
- Stel `Q` gelijk aan de eenheidsmatrix van grootte `n`.
- Voor `i` van `0` t.e.m. `n-2`:
    - Stel `k` gelijk aan de `i`-de kolom van `R`, maar stel de componenten met index kleiner dan `i` gelijk aan nul. (Gebruik hiervoor de methode `maak_nul`.)
    - Stel $u \gets k - \lVert k\rVert \mathbf{e}_i$, waarbij $\mathbf{e}_i$ de $i$-de eenheidsvector is. (Gebruik hiervoor de methode `eenheidsvector`.)
    - Stel `H` gelijk aan de matrix die een Householder reflectie voorstelt met als argument `u`. (Gebruik hiervoor de methode `maak_spiegeling`.)
    - Stel `R` gelijk aan de matrixproduct van `H` en `R`.
    - Stel `Q` gelijk aan de matrixproduct van `Q` en de getransponeerde van `H`.
  
Retourneer een tupel `(Q, R)`.

Belangrijke opmerking: na het uitvoeren van de methode mag de matrix `A` niet aangepast zijn.


In [ ]:
def QR(A):
    ### JOUW CODE HIER
      for i in range(len(A) - 1) :
        maak_spiegeling(A)

      Q = np.eye(len(A))
      R = np.copy(A)
      for i in range(len(A) - 2):
        k =
        H = maak_spiegeling()
        R = H @ R
        Q = Q @ H

      return tuple(Q, R)
    ### EINDE JOUW CODE HIER

Schrijf code om jouw implementatie van de QR-decompositie te testen.
Genereer hiertoe 100 random vierkante matrices van grootte $10\times 10$.
Per matrix controleer je
- of de QR-decompositie correct is door opnieuw A te berekenen aan de hand van Q en R.
- of de matrix $\mathbf{Q}$ orthogonaal is.
- of de matrix $\mathbf{R}$ een bovendriehoeksmatrix is. Gebruik de functie np.triu of np.tril.

In [ ]:
rng = np.random.default_rng()
for _ in range(100):
### JOUW CODE HIER
   a = rng.standard_normal(size=(10, 10)) * 10
   QR(a)

   assert np.linalg.norm(Q) == 1, "geen orthogonale matrix"
   assert R == np.triu(R), "geen bovendriehoeksmatrix"
### EINDE JOUW CODE HIER
print("Alle testen geslaagd")

## Vraag 3. Best passende cirkel (/14)

Hieronder vind je datapunten $\mathbf{x}$ en $\mathbf{y}$.
Deze stellen de coördinaten voor van 10 punten in het $XY$-vlak.


In [ ]:
x = np.array([-4.0,-3,-3,-1,-1,3,4,7,7,8])
y = np.array([3.0,6,0,9,-2,-3,9,6,-1,4])

Maak een scatterplot van deze punten, voor $y$ in functie van $x$.   (/1)  
Zorg dat dezelfde schaal gebruikt wordt op de $X$- en $Y$-as.
Dit kan met de code `plt.axis("square");`

In [ ]:
### JOUW CODE HIER ###

### EINDE JOUW CODE HIER ###

Zoals je kan zien liggen de punten bijna op een cirkel. We willen nu de best passende cirkel vinden, m.a.w. de cirkel die zo dicht mogelijk bij deze punten ligt.
We stellen de cirkel voor met de vergelijking
$$
x^2 + y^2 + \alpha_x\, x + \alpha_y\, y + \alpha_0 = 0
$$
waarbij $\alpha_x$, $\alpha_y$ en $\alpha_0$ de parameters zijn die we willen vinden.

Als alle punten op de cirkel zouiden liggen, dan voldoen ze aan de vergelijking van de cirkel. We kunnen dus een stelsel lineaire vergelijkingen opstellen waarbij we voor elk punt de vergelijking van de cirkel invullen.
Bv. voor het eerste punt $(-4,3)$ krijgen we:
$$
-4\alpha_x + 3\alpha_y + \alpha_0 = -\bigl( (-4)^2 + 3^2 \bigr) = -25
$$
Als we dit doen doen voor alle punten, dan
krijgen we een (hoogstwaarschijnlijk) strijdig stelsel vergelijkingen:
$$
\mathbf{A} \begin{bmatrix} \alpha_x \\ \alpha_y \\ \alpha_0 \end{bmatrix} = \mathbf{b}.
$$

Stel de matrix $\mathbf{A}$ en het rechterlid $\mathbf{b}$ op.

In [ ]:
### JOUW CODE HIER
 A =
 b =
### EINDE JOUW CODE HIER ###

Vind de beste benaderende oplossing van dit stelsel m.b.v. de technieken uit de cursus.

In [ ]:
### JOUW CODE HIER
(A.shape[::-1] * A) * A.shape[::-1] * b
### EINDE JOUW CODE HIER ###

Geef de vergelijking van de best passende cirkel waarbij je de gevonden waarden voor $\alpha_x$, $\alpha_y$ en $\alpha_0$ afrondt op 1 decimaal.
HIER ANTWOORDEN.

We kunnen de vergelijking van de cirkel $x^2 + y^2 + \alpha_x\, x + \alpha_y\, y + \alpha_0 = 0$ herschrijven als:
$$
(x + \alpha_x/2)^2 + (y + \alpha_y/2)^2 = \alpha_x^2/4 + \alpha_y^2/4 - \alpha_0
$$

Vergelijk dit met de vergelijking van een cirkel met middelpunt $(x_0, y_0)$ en straal $r$:
$$
(x - x_0)^2 + (y - y_0)^2 = r^2
$$

Schrijf code om $x_0$, $y_0$ en $r$ te berekenen op basis van de gevonden waarden voor $\alpha_x$, $\alpha_y$ en $\alpha_0$.
```python
x0 = ...
y0 = ...
r = ...
```

In [ ]:
### JOUW CODE HIER
 alpha = (rng.uniform(1) - 0.5) * 10
### EINDE JOUW CODE HIER ###

De punten van een cirkel met middelpunt $(x_0, y_0)$ en straal $r$ kunnen ook beschreven worden als
$$
x = x_0 + r \cos(t) \quad \text{en} \quad y = y_0 + r \sin(t)\quad\text{met}\ t \in [0, 2\pi]
$$

Schrijf code om de best passende cirkel te plotten samen met de punten.  (Hint: `np.pi` bevat de waarde $\pi$.)
Zorg opnieuw dat de ijk van de assen gelijk is. Zorg dat de kleur van de cirkel rood is.

In [ ]:
### JOUW CODE HIER

### EINDE JOUW CODE HIER ###