In [4]:
import numpy as np

In [53]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [4,5,6], [4,5,6]])

product = a @ b
product

c = np.array([1,2,3])
d = np.array([4,5,6])
inwedig_product = np.dot(c, d)
inwedig_product

np.int64(32)

In [59]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped = array.reshape(2, 3)  # Hervorm naar 2x3 matrix
print(reshaped)

print(array[0])  # Eerste element: 1
print(reshaped[1, 2])  # Element op rij 1, kolom 2: 6
print(reshaped[:, 1])  # Tweede kolom: [2 5]

[[1 2 3]
 [4 5 6]]
1
6
[2 5]


In [11]:
a = np.array([[1,2,3], [4,5,6]])
a
a = a.reshape(3, 2)
a
som = np.sum(a, axis=0)
som

array([ 9, 12])

In [21]:
a = np.arange(1,201)
a = a[::-1]
a = a.reshape(20,10)
a

array([[200, 199, 198, 197, 196, 195, 194, 193, 192, 191],
       [190, 189, 188, 187, 186, 185, 184, 183, 182, 181],
       [180, 179, 178, 177, 176, 175, 174, 173, 172, 171],
       [170, 169, 168, 167, 166, 165, 164, 163, 162, 161],
       [160, 159, 158, 157, 156, 155, 154, 153, 152, 151],
       [150, 149, 148, 147, 146, 145, 144, 143, 142, 141],
       [140, 139, 138, 137, 136, 135, 134, 133, 132, 131],
       [130, 129, 128, 127, 126, 125, 124, 123, 122, 121],
       [120, 119, 118, 117, 116, 115, 114, 113, 112, 111],
       [110, 109, 108, 107, 106, 105, 104, 103, 102, 101],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31

In [15]:
matrix = np.ones((10, 10), dtype=int)
matrix[1:9, 2:8] = 0

matrix

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [23]:
import numpy as np

# Stap 1: Maak een 4x3 matrix met de kwadraten van 0 t/m 11
matrix = np.array([i**2 for i in range(12)]).reshape(4, 3)
print(matrix)
gemiddelde = np.mean(matrix, axis=0)
gemiddelde

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


array([31.5, 41.5, 53.5])

In [ ]:
a = np.ones((10, 10))
# a[1:9, 2:8] = 0
a[1:3, 1:9] = 0
a[3:9, 4:6] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
a = np.ones((10, 10))
a[1, 8] = 5
a[2, 7] = 6
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 5., 1.],
       [1., 1., 1., 1., 1., 1., 1., 6., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Methode `maak_nul` (/2)

Implementeer een methode `maak_nul(x, index)` die een numpy array `x` en een index `index` meekrijgt en een array retourneert waarbij alle elementen vanaf index `0` t.e.m. index `index-1` gelijk zijn aan nul. Alle andere elementen blijven ongewijzigd.  Je mag de originele array `x` niet aanpassen! Hieronder een voorbeeld:

```python
maak_nul(np.array([-1, -2, 3, 4, 5]), 2)  # array([0,0,3,4,5])
```

In [3]:
import numpy as np

In [53]:
def maak_nul(x, index):
    # lengte = len(x)
    x[:index] = 0
    return x

In [56]:
print(maak_nul(np.array([-1, -2, 3, 4, 5]), 2))

[0 0 3 4 5]


#### Methode `eenheidsvector` (/2)

Implementeer een methode `eenheidsvector(n, i)` die een numpy array van lengte `n` teruggeeft
bestaande uit nullen behalve het element op plaats `i` dat gelijk is aan 1.

```python
eenheidsvector(5, 3)  # array([0., 0., 0., 1., 0.])

In [17]:
def eenheidsvector(n, i):
    a = np.zeros(n)
    a[i] = 1
    return a

In [18]:
print(eenheidsvector(5, 3))

[0. 0. 0. 1. 0.]


#### Methode `maak_spiegeling` (/3)

Schrijf een methode `maak_spiegeling(u)` die een numpy array `u` meekrijgt en een matrix retourneert die een Householder reflectie voorstelt.

De Householder reflectie is gedefinieerd als:
$$
\mathbf{H} = \mathbf{I} - 2\mathbf{v}\mathbf{v}^T,\quad \text{met } \mathbf{v} = \frac{\mathbf{u}}{\lVert \mathbf{u}\rVert}.
$$
Hierbij is $\mathbf{I}$ de eenheidsmatrix van de gepaste grootte en $\mathbf{v}\mathbf{v}^T$ is het **uitwendig product** van $\mathbf{v}$ met zichzelf.

Je kan wiskundig controleren dat $\mathbf{H}$ een orthogonale matrix is (maar je moet dit niet doen in deze opgave).

In [59]:
def maak_spiegeling(u):
    v = u / np.linalg.norm(u)
    I = np.eye(len(u))
    return I - 2 * np.outer(v, v.T)

#### Implementatie van de QR-decompositie (/15)

Gegeven een vierkante  $n\times n$ matrix $\mathbf{A}$. De QR-decompositie van $\mathbf{A}$ wordt berekend door het uitvoeren van $n-1$ Householder reflecties.

In het bijzonder werkt de QR-decompositie als volgt:
- Stel `R` gelijk aan de originele matrix `A` (maar let op dat je `A` niet aanpast).
- Stel `Q` gelijk aan de eenheidsmatrix van grootte `n`.
- Voor `i` van `0` t.e.m. `n-2`:
    - Stel `k` gelijk aan de `i`-de kolom van `R`, maar stel de componenten met index kleiner dan `i` gelijk aan nul. (Gebruik hiervoor de methode `maak_nul`.)
    - Stel $u \gets k - \lVert k\rVert \mathbf{e}_i$, waarbij $\mathbf{e}_i$ de $i$-de eenheidsvector is. (Gebruik hiervoor de methode `eenheidsvector`.)
    - Stel `H` gelijk aan de matrix die een Householder reflectie voorstelt met als argument `u`. (Gebruik hiervoor de methode `maak_spiegeling`.)
    - Stel `R` gelijk aan de matrixproduct van `H` en `R`.
    - Stel `Q` gelijk aan de matrixproduct van `Q` en de getransponeerde van `H`.
  
Retourneer een tupel `(Q, R)`.

Belangrijke opmerking: na het uitvoeren van de methode mag de matrix `A` niet aangepast zijn.

In [60]:
def QR(A):
    R = A.copy()
    n = len(A)
    Q = np.eye(n)
    # for i in range(n-2):
    for i in range(n):
        k = R[:,i]
        k = maak_nul(k, i)
        u = k - np.linalg.norm(k) * eenheidsvector(len(k), i)
        H = maak_spiegeling(u)
        R = H @ R
        Q = Q @ H.T
    return (Q, R)

In [ ]:
A = np.arange(16).reshape(4,4)
(Q, R) = QR(A)

[[ 1.49666295e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.23446802e-15  1.19522861e+00  0.00000000e+00  0.00000000e+00]
 [-1.09700146e-15  8.47174268e-17  1.33283853e-15  0.00000000e+00]
 [-6.99821333e-16 -9.43221046e-17 -9.98625875e-32  4.73576894e-16]]

[[1.49666295e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.19522861e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.33283853e-15 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.73576894e-16]]


Schrijf code om jouw implementatie van de QR-decompositie te testen.
Genereer hiertoe 100 random vierkante matrices van grootte $10\times 10$.
Per matrix controleer je
- of de QR-decompositie correct is door opnieuw A te berekenen aan de hand van Q en R.
- of de matrix $\mathbf{Q}$ orthogonaal is.
- of de matrix $\mathbf{R}$ een bovendriehoeksmatrix is. Gebruik de functie np.triu of np.tril.

In [ ]:
for _ in range(100):
    rng = np.random.default_rng()
    A = rng.standard_normal((10,10))
    (Q, R) = QR(A)
    assert np.allclose(A, Q @ R), "A is niet gelijk aan Q * R"
    assert np.allclose(Q.T @ Q, np.eye(10)), "Q is niet orthogonaal"
    assert np.allclose(R, np.triu(R)), "R is niet bovendriehoek"

C:\Users\ruben\AppData\Local\Temp\ipykernel_36360\2120915284.py:2: RuntimeWarning: invalid value encountered in divide
  v = u / np.linalg.norm(u)


AssertionError: R is niet bovendriehoek

In [ ]:
x = np.array([-4.0,-3,-3,-1,-1,3,4,7,7,8])
y = np.array([3.0,6,0,9,-2,-3,9,6,-1,4])